name: everyday-publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version of the grammarless extension
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this repository
        uses: actions/checkout@v2
        with:
          path: grammarless-vscode-markdown
      - name: Clone other repository
        uses: actions/checkout@v2
        with:
          repository: yzhang-gh/vscode-markdown
          token: ${{ github.token }}
          path: vscode-markdown
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: npm
          cache-dependency-path: vscode-markdown/package-lock.json
      - name: Run script
        run: |
          python3 grammarless-vscode-markdown/modify.py --dir vscode-markdown --republish --version "${{ github.event.inputs.message }}"
      - name: Install dependencies
        run: |
          cd vscode-markdown
          npm ci
          cd ..
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1.0.7
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          packagePath: 'vscode-markdown'
